### PR TITLE
RSA key length requirement for simple hosting

### PR DESCRIPTION
**Pull request by bcien**
Added RSA key length requirement for simple hosting to the readme.

### CODE REVIEW

**Comment by baloo** [comment]
I believe we are doing things wrong here. We should allow a 4096 key length on simple hosting. I'd prefer not to merge this and fix it on our end.
I will loop internally see if we get this fixed quickly.
Thanks for raising the issue.

**Comment by baloo** [comment]
2048 key-length is actually the default value in certbot. There is a discussion here: https://github.com/certbot/certbot/issues/2080 on changing the default value.

The commit introducing the limit on our end reads "We can't accept anymore RSA key > 2048 bits for hosted certificates, such key size is too expensive for CPU even with Xeon ones".
Running a quick benchmark on a fairly recent CPU (`Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz`) reads:

```
# openssl speed rsa2048 rsa4096
[...]
                  sign    verify    sign/s verify/s
rsa 2048 bits 0.001307s 0.000038s    765.1  26088.3
rsa 4096 bits 0.009643s 0.000141s    103.7   7104.9
```

The impacts of changing this value looks still too high (100 new connection without tls ticket per core vs 765), as it's not the default in certbot. I will merge this. I subscribed to the certbot issue and make sure we reconsider this once situation evolves.

Thanks!

**Comment by bcien** [comment]
Thanks for the number about the server load. I was expecting a lower impact too, but still glad the factor is lower than a factor of 10 (around 7 for sign and 4 for verify). 

As the default key in certbot is 2048 bits, probably a change in Simple Hosting to allow 4096 bit keys wont necessary result in a higher server load, but as Gandi has no control over certbot defaults, it won't be a good idea if the servers are not fast enough to handle the expected load, if certbot decides to move to 4096 bits (which will eventually happen). 

Anyways, should the server load at Gandi be limited by the instance size? In that case, if the expected impact in a simulation is much higher, maybe 4096 bit keys could be enabled for instances with more resources (for example, size L), although probably small size M instances may notice no difference at all.

**Comment by baloo** [comment]
Sadly we do not care much about the verify factor on our end as we do not support client certificate.

**Pull request merged**
